[package]
name = "bradley"
version = "1.0.1"
edition = "2021"

[[bin]]
name = "bradley"
path = "src/main.rs"

[dependencies]
winit = "0.29"
wgpu = "0.19"
image = "0.24"
pollster = "0.3"
tray-icon = "0.14"

[build-dependencies]
image = "0.24"